name: 'doc ðŸ‡¯ðŸ‡µï¸'

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '21 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: |
        mkdir target
        docker run -v .:/doc -u $(id -u) axonivy/build-container:read-the-docs-2 make html BASEDIR=/doc\
         LOCALEDIR=/doc/locale GETTEXT_COMPACT=user-guide SPHINXOPTS="-D language='ja'"\
         2> target/sphinx-errors.log
        cat target/sphinx-errors.log\
         | sed -E 's|/doc/(.*\.rst):([0-9]+): ([A-Za-z]*): |::\L\3 file=\1,line=\2::|g'\
         | grep -v "image.not_readable"\
         | grep -v "/target/"\
         | grep -v "Could not obtain image"\
         | grep -v "Cannot scale image!"
    - name: Archive build artifact
      uses: actions/upload-artifact@v5
      with:
        name: axonivy-doc_jp
        path: |
          build/html/**/*
