name: i18n

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron:  '21 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: POT Templates
      run: | 
        version=dev
        ./substitute.sh ${version}
        docker run -v .:/doc -u $(id -u) axonivy/build-container:read-the-docs-2 make gettext BASEDIR=/doc
    - name: Update PO Languages
      run: |
        docker run -v .:/doc -u $(id -u) axonivy/build-container:read-the-docs-2 make\
          generatePO BASEDIR=/doc LOCALEDIR=/doc/locale LANGUAGE=ja
    - name: Configure Git
      run: |
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
    - name: Create Pull Request
      run: |
        git checkout -b languages
        if [ ! -z `git --no-pager diff` ]; then
          git add locale/*
          git commit -m "update PO language files"
          git push -u -f origin languages
          gh pr create --title "Language update :globe_with_meridians:"\
            --body "auto-updates language files"\
            --label "i18n"
        fi
      env:
        GH_TOKEN: ${{ github.token }}
